version: "3.9"

services:
  db:
    image: postgres:16
    container_name: latambeauty-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
